# -*- coding: utf-8 -*-
"""Copy of Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUDaHZ1sPFPUEKNeESs5HpsBNtQMha4a
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/Diwali Sales Data.csv', encoding = 'unicode_escape')

df.head()

df.shape

df.info()

df.drop(['Status', 'unnamed1'], axis = 1, inplace = True)

df.info()

df.isnull().sum()

df.dropna(inplace = True)

df.shape

df['Amount'] = df['Amount'].astype('int')

df['Amount'].dtypes

"""EXPLORING DATA TYPE"""

df.columns

ax = sns.countplot(x = 'Gender', data = df)
for bars in ax.containers:
  ax.bar_label(bars)

"""females are purchased more than men"""

sales_gen = df.groupby(['Gender'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.barplot(x = 'Gender', y = 'Amount', data = sales_gen)

"""in this also females spend more money than men

AGE
"""

df.columns

ax = sns.countplot(x = 'Age Group', data = df, hue = 'Gender')
for bars in ax.containers:
  ax.bar_label(bars)

"""By above analysis we can say age group between 26-35 are buying more"""

sales_age = df.groupby(['Age Group'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.barplot(x = 'Age Group', y = 'Amount', data = sales_age)

"""STATE"""

sales_state = df.groupby(['State'], as_index = False)['Orders'].sum().sort_values(by = 'Orders', ascending = False).head(10)
sns.set(rc = {'figure.figsize' : (30, 10)})
sns.barplot(x = 'State', y = 'Orders', data = sales_state, hue = 'State', legend = False)

"""frpm above diagram we can say UP people are buying more then after maharashtra,karnataka,delhi"""

sales_state = df.groupby(['State'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False).head(10)
sns.set(rc = {'figure.figsize' : (30, 10)})
sns.barplot(x = 'State', y = 'Amount', data = sales_state, hue = 'State', legend = False)

"""MARITAL STATUS"""

ax = sns.countplot(x = 'Marital_Status', data = df, hue = 'Gender')
for bars in ax.containers:
  ax.bar_label(bars)

sales_status = df.groupby(['Marital_Status', 'Gender'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.set(rc = {'figure.figsize' : (10, 5)})
sns.barplot(x = 'Marital_Status', y = 'Amount', data = sales_status, hue = 'Gender')

"""OCCUPATION"""

sns.set(rc = {'figure.figsize' : (30, 15)})
ax = sns.countplot(x = 'Occupation', data = df, hue = 'Gender')
for bars in ax.containers:
  ax.bar_label(bars)

sales_occupation = df.groupby(['Occupation'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)
sns.set(rc = {'figure.figsize' : (30, 10)})
sns.barplot(x = 'Occupation', y = 'Amount', data = sales_occupation, hue = 'Occupation', legend = False)

"""from above we can say IT sector,Healthcare,Avaition people are buying more products

PRODUCT CATEGORY
"""

df.columns

sns.set(rc = {'figure.figsize' : (30, 15)})
ax = sns.countplot(x = 'Product_Category', data = df, hue = 'Gender',width=0.9)
for bars in ax.containers:
  ax.bar_label(bars)

sales_category = df.groupby(['Product_Category'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False).head(10)
sns.set(rc = {'figure.figsize' : (30, 10)})
sns.barplot(x = 'Product_Category', y = 'Amount', data = sales_category, hue = 'Product_Category', legend = False)

"""people are spending more money in food,clothing,electronics

*CONCLUTION*

married women from age 26-35 from states UP,maharastra,karnataka occupation IT sector,healthcare,Aviation are spending more on food,clothing and electronics
"""